name: backend-ci-cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff

      - name: Verify code with Ruff
        run: |
          python -m ruff check .
          python -m ruff format --check .

      - name: Create .env and start topology
        run: |
          echo "${{ secrets.POSTGRE_ADMINS }}" > .env
          echo "${{ secrets.URLS }}" >> .env
          docker compose up postgres_auth postgres_university auth university -d
          docker compose run backend-tests
          
      - name: Read log for postgres_university container
        if: failure()
        run: |
          docker compose logs postgres_university
          docker compose logs postgres_auth

      - name: Load Allure history and Generate Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: 'allure-results'
          allure_report: 'allure-report'

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
