name: backend-ci-cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v8
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv pip install ".[dev]"

      - name: Verify code with ruff
        run: |
          uv run ruff check .
          uv run -m ruff format --check .

      - name: Create .env and start topology
        run: |
          echo "${{ secrets.POSTGRE_ADMINS }}" > .env
          echo "${{ secrets.URLS }}" >> .env
          docker compose up postgres_auth postgres_university auth university -d
          docker compose run backend-tests

      - name: Load Allure history and Generate Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: 'allure-results'
          allure_report: 'allure-report'

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report